"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import RhoTypes_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class ApprovedBlockProto(google.protobuf.message.Message):
    """---------- Approved block ---------

    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    BLOCK_FIELD_NUMBER: builtins.int
    @property
    def block(self) -> global___BlockMessageProto: ...
    def __init__(self,
        *,
        block: typing.Optional[global___BlockMessageProto] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["block",b"block"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["block",b"block"]) -> None: ...
global___ApprovedBlockProto = ApprovedBlockProto

class ApprovedBlockRequestProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    IDENTIFIER_FIELD_NUMBER: builtins.int
    TRIMSTATE_FIELD_NUMBER: builtins.int
    identifier: typing.Text
    trimState: builtins.bool
    def __init__(self,
        *,
        identifier: typing.Text = ...,
        trimState: builtins.bool = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["identifier",b"identifier","trimState",b"trimState"]) -> None: ...
global___ApprovedBlockRequestProto = ApprovedBlockRequestProto

class NoApprovedBlockAvailableProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    IDENTIFIER_FIELD_NUMBER: builtins.int
    NODEIDENTIFER_FIELD_NUMBER: builtins.int
    identifier: typing.Text
    nodeIdentifer: typing.Text
    def __init__(self,
        *,
        identifier: typing.Text = ...,
        nodeIdentifer: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["identifier",b"identifier","nodeIdentifer",b"nodeIdentifer"]) -> None: ...
global___NoApprovedBlockAvailableProto = NoApprovedBlockAvailableProto

class ForkChoiceTipRequestProto(google.protobuf.message.Message):
    """------- End Approved block --------

    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self,
        ) -> None: ...
global___ForkChoiceTipRequestProto = ForkChoiceTipRequestProto

class HasBlockRequestProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    HASH_FIELD_NUMBER: builtins.int
    hash: builtins.bytes
    def __init__(self,
        *,
        hash: builtins.bytes = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["hash",b"hash"]) -> None: ...
global___HasBlockRequestProto = HasBlockRequestProto

class HasBlockProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    HASH_FIELD_NUMBER: builtins.int
    hash: builtins.bytes
    def __init__(self,
        *,
        hash: builtins.bytes = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["hash",b"hash"]) -> None: ...
global___HasBlockProto = HasBlockProto

class BlockRequestProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    HASH_FIELD_NUMBER: builtins.int
    hash: builtins.bytes
    def __init__(self,
        *,
        hash: builtins.bytes = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["hash",b"hash"]) -> None: ...
global___BlockRequestProto = BlockRequestProto

class BlockHashMessageProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    HASH_FIELD_NUMBER: builtins.int
    BLOCKCREATOR_FIELD_NUMBER: builtins.int
    hash: builtins.bytes
    blockCreator: builtins.bytes
    def __init__(self,
        *,
        hash: builtins.bytes = ...,
        blockCreator: builtins.bytes = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["blockCreator",b"blockCreator","hash",b"hash"]) -> None: ...
global___BlockHashMessageProto = BlockHashMessageProto

class BlockMessageProto(google.protobuf.message.Message):
    """--------- Core Protocol  --------

    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    VERSION_FIELD_NUMBER: builtins.int
    SHARDID_FIELD_NUMBER: builtins.int
    BLOCKHASH_FIELD_NUMBER: builtins.int
    BLOCKNUMBER_FIELD_NUMBER: builtins.int
    SENDER_FIELD_NUMBER: builtins.int
    SEQNUM_FIELD_NUMBER: builtins.int
    PRESTATEHASH_FIELD_NUMBER: builtins.int
    POSTSTATEHASH_FIELD_NUMBER: builtins.int
    JUSTIFICATIONS_FIELD_NUMBER: builtins.int
    BONDS_FIELD_NUMBER: builtins.int
    REJECTEDDEPLOYS_FIELD_NUMBER: builtins.int
    REJECTEDBLOCKS_FIELD_NUMBER: builtins.int
    REJECTEDSENDERS_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    SIGALGORITHM_FIELD_NUMBER: builtins.int
    SIG_FIELD_NUMBER: builtins.int
    version: builtins.int
    """version number to define how block is serialized and hashed"""

    shardId: typing.Text
    """identifier of the shard where the block was created"""

    blockHash: builtins.bytes
    """obtained by hashing all information in the block except signature"""

    blockNumber: builtins.int
    sender: builtins.bytes
    """public key of the validator that created the block"""

    seqNum: builtins.int
    """number of blocks created by the validator"""

    preStateHash: builtins.bytes
    """hash of the tuplespace contents before new deploys"""

    postStateHash: builtins.bytes
    """hash of the tuplespace contents after new deploys"""

    @property
    def justifications(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]:
        """map of all validators to latest blocks based on current view"""
        pass
    @property
    def bonds(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___BondProto]:
        """validators and their stakes"""
        pass
    @property
    def rejectedDeploys(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]:
        """Rejected data in finalized fringe"""
        pass
    @property
    def rejectedBlocks(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    @property
    def rejectedSenders(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    @property
    def state(self) -> global___RholangStateProto:
        """Rholang execution trace"""
        pass
    sigAlgorithm: typing.Text
    """Block signature
    name of the algorithm used to sign
    """

    sig: builtins.bytes
    """signature generated by signing blockHash"""

    def __init__(self,
        *,
        version: builtins.int = ...,
        shardId: typing.Text = ...,
        blockHash: builtins.bytes = ...,
        blockNumber: builtins.int = ...,
        sender: builtins.bytes = ...,
        seqNum: builtins.int = ...,
        preStateHash: builtins.bytes = ...,
        postStateHash: builtins.bytes = ...,
        justifications: typing.Optional[typing.Iterable[builtins.bytes]] = ...,
        bonds: typing.Optional[typing.Iterable[global___BondProto]] = ...,
        rejectedDeploys: typing.Optional[typing.Iterable[builtins.bytes]] = ...,
        rejectedBlocks: typing.Optional[typing.Iterable[builtins.bytes]] = ...,
        rejectedSenders: typing.Optional[typing.Iterable[builtins.bytes]] = ...,
        state: typing.Optional[global___RholangStateProto] = ...,
        sigAlgorithm: typing.Text = ...,
        sig: builtins.bytes = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["state",b"state"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["blockHash",b"blockHash","blockNumber",b"blockNumber","bonds",b"bonds","justifications",b"justifications","postStateHash",b"postStateHash","preStateHash",b"preStateHash","rejectedBlocks",b"rejectedBlocks","rejectedDeploys",b"rejectedDeploys","rejectedSenders",b"rejectedSenders","sender",b"sender","seqNum",b"seqNum","shardId",b"shardId","sig",b"sig","sigAlgorithm",b"sigAlgorithm","state",b"state","version",b"version"]) -> None: ...
global___BlockMessageProto = BlockMessageProto

class DeployDataProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DEPLOYER_FIELD_NUMBER: builtins.int
    TERM_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    SIG_FIELD_NUMBER: builtins.int
    SIGALGORITHM_FIELD_NUMBER: builtins.int
    PHLOPRICE_FIELD_NUMBER: builtins.int
    PHLOLIMIT_FIELD_NUMBER: builtins.int
    VALIDAFTERBLOCKNUMBER_FIELD_NUMBER: builtins.int
    SHARDID_FIELD_NUMBER: builtins.int
    deployer: builtins.bytes
    """public key"""

    term: typing.Text
    """Rholang source code to deploy (will be parsed into `Par`)"""

    timestamp: builtins.int
    """number for user to create different signature for the same deploy data"""

    sig: builtins.bytes
    """signature of (hash(term) + timestamp) using private key"""

    sigAlgorithm: typing.Text
    """name of the algorithm used to sign"""

    phloPrice: builtins.int
    """phlo price"""

    phloLimit: builtins.int
    """phlo limit for the deployment"""

    validAfterBlockNumber: builtins.int
    shardId: typing.Text
    """shard ID to prevent replay of deploys between shards"""

    def __init__(self,
        *,
        deployer: builtins.bytes = ...,
        term: typing.Text = ...,
        timestamp: builtins.int = ...,
        sig: builtins.bytes = ...,
        sigAlgorithm: typing.Text = ...,
        phloPrice: builtins.int = ...,
        phloLimit: builtins.int = ...,
        validAfterBlockNumber: builtins.int = ...,
        shardId: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["deployer",b"deployer","phloLimit",b"phloLimit","phloPrice",b"phloPrice","shardId",b"shardId","sig",b"sig","sigAlgorithm",b"sigAlgorithm","term",b"term","timestamp",b"timestamp","validAfterBlockNumber",b"validAfterBlockNumber"]) -> None: ...
global___DeployDataProto = DeployDataProto

class RholangStateProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DEPLOYS_FIELD_NUMBER: builtins.int
    SYSTEMDEPLOYS_FIELD_NUMBER: builtins.int
    @property
    def deploys(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ProcessedDeployProto]: ...
    @property
    def systemDeploys(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ProcessedSystemDeployProto]: ...
    def __init__(self,
        *,
        deploys: typing.Optional[typing.Iterable[global___ProcessedDeployProto]] = ...,
        systemDeploys: typing.Optional[typing.Iterable[global___ProcessedSystemDeployProto]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["deploys",b"deploys","systemDeploys",b"systemDeploys"]) -> None: ...
global___RholangStateProto = RholangStateProto

class ProcessedDeployProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DEPLOY_FIELD_NUMBER: builtins.int
    COST_FIELD_NUMBER: builtins.int
    DEPLOYLOG_FIELD_NUMBER: builtins.int
    ERRORED_FIELD_NUMBER: builtins.int
    SYSTEMDEPLOYERROR_FIELD_NUMBER: builtins.int
    @property
    def deploy(self) -> global___DeployDataProto:
        """user deploy"""
        pass
    @property
    def cost(self) -> RhoTypes_pb2.PCost:
        """cost for execution of user deploy"""
        pass
    @property
    def deployLog(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___EventProto]:
        """Rholang execution trace for deploy"""
        pass
    errored: builtins.bool
    """true if deploy encountered a user error"""

    systemDeployError: typing.Text
    """error message for system deploy"""

    def __init__(self,
        *,
        deploy: typing.Optional[global___DeployDataProto] = ...,
        cost: typing.Optional[RhoTypes_pb2.PCost] = ...,
        deployLog: typing.Optional[typing.Iterable[global___EventProto]] = ...,
        errored: builtins.bool = ...,
        systemDeployError: typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["cost",b"cost","deploy",b"deploy"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["cost",b"cost","deploy",b"deploy","deployLog",b"deployLog","errored",b"errored","systemDeployError",b"systemDeployError"]) -> None: ...
global___ProcessedDeployProto = ProcessedDeployProto

class SlashSystemDeployDataProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SLASHEDVALIDATOR_FIELD_NUMBER: builtins.int
    slashedValidator: builtins.bytes
    def __init__(self,
        *,
        slashedValidator: builtins.bytes = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["slashedValidator",b"slashedValidator"]) -> None: ...
global___SlashSystemDeployDataProto = SlashSystemDeployDataProto

class CloseBlockSystemDeployDataProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self,
        ) -> None: ...
global___CloseBlockSystemDeployDataProto = CloseBlockSystemDeployDataProto

class SystemDeployDataProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SLASHSYSTEMDEPLOY_FIELD_NUMBER: builtins.int
    CLOSEBLOCKSYSTEMDEPLOY_FIELD_NUMBER: builtins.int
    @property
    def slashSystemDeploy(self) -> global___SlashSystemDeployDataProto: ...
    @property
    def closeBlockSystemDeploy(self) -> global___CloseBlockSystemDeployDataProto: ...
    def __init__(self,
        *,
        slashSystemDeploy: typing.Optional[global___SlashSystemDeployDataProto] = ...,
        closeBlockSystemDeploy: typing.Optional[global___CloseBlockSystemDeployDataProto] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["closeBlockSystemDeploy",b"closeBlockSystemDeploy","slashSystemDeploy",b"slashSystemDeploy","systemDeploy",b"systemDeploy"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["closeBlockSystemDeploy",b"closeBlockSystemDeploy","slashSystemDeploy",b"slashSystemDeploy","systemDeploy",b"systemDeploy"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["systemDeploy",b"systemDeploy"]) -> typing.Optional[typing_extensions.Literal["slashSystemDeploy","closeBlockSystemDeploy"]]: ...
global___SystemDeployDataProto = SystemDeployDataProto

class ProcessedSystemDeployProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SYSTEMDEPLOY_FIELD_NUMBER: builtins.int
    DEPLOYLOG_FIELD_NUMBER: builtins.int
    ERRORMSG_FIELD_NUMBER: builtins.int
    @property
    def systemDeploy(self) -> global___SystemDeployDataProto: ...
    @property
    def deployLog(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___EventProto]: ...
    errorMsg: typing.Text
    def __init__(self,
        *,
        systemDeploy: typing.Optional[global___SystemDeployDataProto] = ...,
        deployLog: typing.Optional[typing.Iterable[global___EventProto]] = ...,
        errorMsg: typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["systemDeploy",b"systemDeploy"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["deployLog",b"deployLog","errorMsg",b"errorMsg","systemDeploy",b"systemDeploy"]) -> None: ...
global___ProcessedSystemDeployProto = ProcessedSystemDeployProto

class RejectedDeployProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SIG_FIELD_NUMBER: builtins.int
    sig: builtins.bytes
    def __init__(self,
        *,
        sig: builtins.bytes = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["sig",b"sig"]) -> None: ...
global___RejectedDeployProto = RejectedDeployProto

class EventProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PRODUCE_FIELD_NUMBER: builtins.int
    CONSUME_FIELD_NUMBER: builtins.int
    COMM_FIELD_NUMBER: builtins.int
    @property
    def produce(self) -> global___ProduceEventProto: ...
    @property
    def consume(self) -> global___ConsumeEventProto: ...
    @property
    def comm(self) -> global___CommEventProto: ...
    def __init__(self,
        *,
        produce: typing.Optional[global___ProduceEventProto] = ...,
        consume: typing.Optional[global___ConsumeEventProto] = ...,
        comm: typing.Optional[global___CommEventProto] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["comm",b"comm","consume",b"consume","event_instance",b"event_instance","produce",b"produce"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["comm",b"comm","consume",b"consume","event_instance",b"event_instance","produce",b"produce"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["event_instance",b"event_instance"]) -> typing.Optional[typing_extensions.Literal["produce","consume","comm"]]: ...
global___EventProto = EventProto

class ProduceEventProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CHANNELSHASH_FIELD_NUMBER: builtins.int
    HASH_FIELD_NUMBER: builtins.int
    PERSISTENT_FIELD_NUMBER: builtins.int
    TIMESREPEATED_FIELD_NUMBER: builtins.int
    channelsHash: builtins.bytes
    hash: builtins.bytes
    persistent: builtins.bool
    timesRepeated: builtins.int
    def __init__(self,
        *,
        channelsHash: builtins.bytes = ...,
        hash: builtins.bytes = ...,
        persistent: builtins.bool = ...,
        timesRepeated: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["channelsHash",b"channelsHash","hash",b"hash","persistent",b"persistent","timesRepeated",b"timesRepeated"]) -> None: ...
global___ProduceEventProto = ProduceEventProto

class ConsumeEventProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CHANNELSHASHES_FIELD_NUMBER: builtins.int
    HASH_FIELD_NUMBER: builtins.int
    PERSISTENT_FIELD_NUMBER: builtins.int
    @property
    def channelsHashes(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    hash: builtins.bytes
    persistent: builtins.bool
    def __init__(self,
        *,
        channelsHashes: typing.Optional[typing.Iterable[builtins.bytes]] = ...,
        hash: builtins.bytes = ...,
        persistent: builtins.bool = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["channelsHashes",b"channelsHashes","hash",b"hash","persistent",b"persistent"]) -> None: ...
global___ConsumeEventProto = ConsumeEventProto

class CommEventProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CONSUME_FIELD_NUMBER: builtins.int
    PRODUCES_FIELD_NUMBER: builtins.int
    PEEKS_FIELD_NUMBER: builtins.int
    @property
    def consume(self) -> global___ConsumeEventProto: ...
    @property
    def produces(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ProduceEventProto]: ...
    @property
    def peeks(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PeekProto]: ...
    def __init__(self,
        *,
        consume: typing.Optional[global___ConsumeEventProto] = ...,
        produces: typing.Optional[typing.Iterable[global___ProduceEventProto]] = ...,
        peeks: typing.Optional[typing.Iterable[global___PeekProto]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["consume",b"consume"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["consume",b"consume","peeks",b"peeks","produces",b"produces"]) -> None: ...
global___CommEventProto = CommEventProto

class PeekProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CHANNELINDEX_FIELD_NUMBER: builtins.int
    channelIndex: builtins.int
    def __init__(self,
        *,
        channelIndex: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["channelIndex",b"channelIndex"]) -> None: ...
global___PeekProto = PeekProto

class BondProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    VALIDATOR_FIELD_NUMBER: builtins.int
    STAKE_FIELD_NUMBER: builtins.int
    validator: builtins.bytes
    stake: builtins.int
    def __init__(self,
        *,
        validator: builtins.bytes = ...,
        stake: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["stake",b"stake","validator",b"validator"]) -> None: ...
global___BondProto = BondProto

class StoreNodeKeyProto(google.protobuf.message.Message):
    """--------- End Core Protocol  --------

    --------- Last finalized state  --------

    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    HASH_FIELD_NUMBER: builtins.int
    INDEX_FIELD_NUMBER: builtins.int
    hash: builtins.bytes
    index: builtins.int
    def __init__(self,
        *,
        hash: builtins.bytes = ...,
        index: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["hash",b"hash","index",b"index"]) -> None: ...
global___StoreNodeKeyProto = StoreNodeKeyProto

class StoreItemsMessageRequestProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STARTPATH_FIELD_NUMBER: builtins.int
    SKIP_FIELD_NUMBER: builtins.int
    TAKE_FIELD_NUMBER: builtins.int
    @property
    def startPath(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___StoreNodeKeyProto]: ...
    skip: builtins.int
    take: builtins.int
    def __init__(self,
        *,
        startPath: typing.Optional[typing.Iterable[global___StoreNodeKeyProto]] = ...,
        skip: builtins.int = ...,
        take: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["skip",b"skip","startPath",b"startPath","take",b"take"]) -> None: ...
global___StoreItemsMessageRequestProto = StoreItemsMessageRequestProto

class StoreItemProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    KEY_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    key: builtins.bytes
    value: builtins.bytes
    def __init__(self,
        *,
        key: builtins.bytes = ...,
        value: builtins.bytes = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["key",b"key","value",b"value"]) -> None: ...
global___StoreItemProto = StoreItemProto

class StoreItemsMessageProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STARTPATH_FIELD_NUMBER: builtins.int
    LASTPATH_FIELD_NUMBER: builtins.int
    HISTORYITEMS_FIELD_NUMBER: builtins.int
    DATAITEMS_FIELD_NUMBER: builtins.int
    @property
    def startPath(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___StoreNodeKeyProto]: ...
    @property
    def lastPath(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___StoreNodeKeyProto]: ...
    @property
    def historyItems(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___StoreItemProto]: ...
    @property
    def dataItems(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___StoreItemProto]: ...
    def __init__(self,
        *,
        startPath: typing.Optional[typing.Iterable[global___StoreNodeKeyProto]] = ...,
        lastPath: typing.Optional[typing.Iterable[global___StoreNodeKeyProto]] = ...,
        historyItems: typing.Optional[typing.Iterable[global___StoreItemProto]] = ...,
        dataItems: typing.Optional[typing.Iterable[global___StoreItemProto]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["dataItems",b"dataItems","historyItems",b"historyItems","lastPath",b"lastPath","startPath",b"startPath"]) -> None: ...
global___StoreItemsMessageProto = StoreItemsMessageProto

class BlockMetadataProto(google.protobuf.message.Message):
    """--------- End Last finalized state  --------

    --------- Internal types ---------

    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    BLOCKHASH_FIELD_NUMBER: builtins.int
    BLOCKNUM_FIELD_NUMBER: builtins.int
    SENDER_FIELD_NUMBER: builtins.int
    SEQNUM_FIELD_NUMBER: builtins.int
    JUSTIFICATIONS_FIELD_NUMBER: builtins.int
    BONDS_FIELD_NUMBER: builtins.int
    INVALID_FIELD_NUMBER: builtins.int
    DIRECTLYFINALIZED_FIELD_NUMBER: builtins.int
    FINALIZED_FIELD_NUMBER: builtins.int
    PARENTS_FIELD_NUMBER: builtins.int
    blockHash: builtins.bytes
    blockNum: builtins.int
    sender: builtins.bytes
    seqNum: builtins.int
    @property
    def justifications(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    @property
    def bonds(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___BondProto]: ...
    invalid: builtins.bool
    """whether the block was marked as invalid"""

    directlyFinalized: builtins.bool
    """whether the block has been last finalized block (LFB)"""

    finalized: builtins.bool
    """whether the block is finalized"""

    @property
    def parents(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    def __init__(self,
        *,
        blockHash: builtins.bytes = ...,
        blockNum: builtins.int = ...,
        sender: builtins.bytes = ...,
        seqNum: builtins.int = ...,
        justifications: typing.Optional[typing.Iterable[builtins.bytes]] = ...,
        bonds: typing.Optional[typing.Iterable[global___BondProto]] = ...,
        invalid: builtins.bool = ...,
        directlyFinalized: builtins.bool = ...,
        finalized: builtins.bool = ...,
        parents: typing.Optional[typing.Iterable[builtins.bytes]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["blockHash",b"blockHash","blockNum",b"blockNum","bonds",b"bonds","directlyFinalized",b"directlyFinalized","finalized",b"finalized","invalid",b"invalid","justifications",b"justifications","parents",b"parents","sender",b"sender","seqNum",b"seqNum"]) -> None: ...
global___BlockMetadataProto = BlockMetadataProto
