# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProposeServiceV1.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import ServiceError_pb2 as ServiceError__pb2
from . import ProposeServiceCommon_pb2 as ProposeServiceCommon__pb2
from .scalapb import scalapb_pb2 as scalapb_dot_scalapb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16ProposeServiceV1.proto\x12\tcasper.v1\x1a\x12ServiceError.proto\x1a\x1aProposeServiceCommon.proto\x1a\x15scalapb/scalapb.proto\"N\n\x0fProposeResponse\x12\x1e\n\x05\x65rror\x18\x01 \x01(\x0b\x32\r.ServiceErrorH\x00\x12\x10\n\x06result\x18\x02 \x01(\tH\x00\x42\t\n\x07message\"T\n\x15ProposeResultResponse\x12\x1e\n\x05\x65rror\x18\x01 \x01(\x0b\x32\r.ServiceErrorH\x00\x12\x10\n\x06result\x18\x02 \x01(\tH\x00\x42\t\n\x07message2\xa0\x01\n\x0eProposeService\x12=\n\x07propose\x12\x14.casper.ProposeQuery\x1a\x1a.casper.v1.ProposeResponse\"\x00\x12O\n\rproposeResult\x12\x1a.casper.ProposeResultQuery\x1a .casper.v1.ProposeResultResponse\"\x00\x42\x31\xe2?.\n&coop.rchain.casper.protocol.propose.v1\x10\x01(\x01H\x00\x62\x06proto3')



_PROPOSERESPONSE = DESCRIPTOR.message_types_by_name['ProposeResponse']
_PROPOSERESULTRESPONSE = DESCRIPTOR.message_types_by_name['ProposeResultResponse']
ProposeResponse = _reflection.GeneratedProtocolMessageType('ProposeResponse', (_message.Message,), {
  'DESCRIPTOR' : _PROPOSERESPONSE,
  '__module__' : 'ProposeServiceV1_pb2'
  # @@protoc_insertion_point(class_scope:casper.v1.ProposeResponse)
  })
_sym_db.RegisterMessage(ProposeResponse)

ProposeResultResponse = _reflection.GeneratedProtocolMessageType('ProposeResultResponse', (_message.Message,), {
  'DESCRIPTOR' : _PROPOSERESULTRESPONSE,
  '__module__' : 'ProposeServiceV1_pb2'
  # @@protoc_insertion_point(class_scope:casper.v1.ProposeResultResponse)
  })
_sym_db.RegisterMessage(ProposeResultResponse)

_PROPOSESERVICE = DESCRIPTOR.services_by_name['ProposeService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\342?.\n&coop.rchain.casper.protocol.propose.v1\020\001(\001H\000'
  _PROPOSERESPONSE._serialized_start=108
  _PROPOSERESPONSE._serialized_end=186
  _PROPOSERESULTRESPONSE._serialized_start=188
  _PROPOSERESULTRESPONSE._serialized_end=272
  _PROPOSESERVICE._serialized_start=275
  _PROPOSESERVICE._serialized_end=435
# @@protoc_insertion_point(module_scope)
