# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import ProposeServiceCommon_pb2 as ProposeServiceCommon__pb2
from . import ProposeServiceV1_pb2 as ProposeServiceV1__pb2


class ProposeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.propose = channel.unary_unary(
                '/casper.v1.ProposeService/propose',
                request_serializer=ProposeServiceCommon__pb2.ProposeQuery.SerializeToString,
                response_deserializer=ProposeServiceV1__pb2.ProposeResponse.FromString,
                )
        self.proposeResult = channel.unary_unary(
                '/casper.v1.ProposeService/proposeResult',
                request_serializer=ProposeServiceCommon__pb2.ProposeResultQuery.SerializeToString,
                response_deserializer=ProposeServiceV1__pb2.ProposeResultResponse.FromString,
                )


class ProposeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def propose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def proposeResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProposeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'propose': grpc.unary_unary_rpc_method_handler(
                    servicer.propose,
                    request_deserializer=ProposeServiceCommon__pb2.ProposeQuery.FromString,
                    response_serializer=ProposeServiceV1__pb2.ProposeResponse.SerializeToString,
            ),
            'proposeResult': grpc.unary_unary_rpc_method_handler(
                    servicer.proposeResult,
                    request_deserializer=ProposeServiceCommon__pb2.ProposeResultQuery.FromString,
                    response_serializer=ProposeServiceV1__pb2.ProposeResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'casper.v1.ProposeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProposeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def propose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/casper.v1.ProposeService/propose',
            ProposeServiceCommon__pb2.ProposeQuery.SerializeToString,
            ProposeServiceV1__pb2.ProposeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def proposeResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/casper.v1.ProposeService/proposeResult',
            ProposeServiceCommon__pb2.ProposeResultQuery.SerializeToString,
            ProposeServiceV1__pb2.ProposeResultResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
