# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProposeServiceCommon.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from .scalapb import scalapb_pb2 as scalapb_dot_scalapb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aProposeServiceCommon.proto\x12\x06\x63\x61sper\x1a\x15scalapb/scalapb.proto\"7\n\x18PrintUnmatchedSendsQuery\x12\x1b\n\x13printUnmatchedSends\x18\x01 \x01(\x08\"\x14\n\x12ProposeResultQuery\"\x1f\n\x0cProposeQuery\x12\x0f\n\x07isAsync\x18\x01 \x01(\x08\x42&\xe2?#\n\x1b\x63oop.rchain.casper.protocol\x10\x01(\x01H\x00\x62\x06proto3')



_PRINTUNMATCHEDSENDSQUERY = DESCRIPTOR.message_types_by_name['PrintUnmatchedSendsQuery']
_PROPOSERESULTQUERY = DESCRIPTOR.message_types_by_name['ProposeResultQuery']
_PROPOSEQUERY = DESCRIPTOR.message_types_by_name['ProposeQuery']
PrintUnmatchedSendsQuery = _reflection.GeneratedProtocolMessageType('PrintUnmatchedSendsQuery', (_message.Message,), {
  'DESCRIPTOR' : _PRINTUNMATCHEDSENDSQUERY,
  '__module__' : 'ProposeServiceCommon_pb2'
  # @@protoc_insertion_point(class_scope:casper.PrintUnmatchedSendsQuery)
  })
_sym_db.RegisterMessage(PrintUnmatchedSendsQuery)

ProposeResultQuery = _reflection.GeneratedProtocolMessageType('ProposeResultQuery', (_message.Message,), {
  'DESCRIPTOR' : _PROPOSERESULTQUERY,
  '__module__' : 'ProposeServiceCommon_pb2'
  # @@protoc_insertion_point(class_scope:casper.ProposeResultQuery)
  })
_sym_db.RegisterMessage(ProposeResultQuery)

ProposeQuery = _reflection.GeneratedProtocolMessageType('ProposeQuery', (_message.Message,), {
  'DESCRIPTOR' : _PROPOSEQUERY,
  '__module__' : 'ProposeServiceCommon_pb2'
  # @@protoc_insertion_point(class_scope:casper.ProposeQuery)
  })
_sym_db.RegisterMessage(ProposeQuery)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\342?#\n\033coop.rchain.casper.protocol\020\001(\001H\000'
  _PRINTUNMATCHEDSENDSQUERY._serialized_start=61
  _PRINTUNMATCHEDSENDSQUERY._serialized_end=116
  _PROPOSERESULTQUERY._serialized_start=118
  _PROPOSERESULTQUERY._serialized_end=138
  _PROPOSEQUERY._serialized_start=140
  _PROPOSEQUERY._serialized_end=171
# @@protoc_insertion_point(module_scope)
