# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ServiceError.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from .scalapb import scalapb_pb2 as scalapb_dot_scalapb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12ServiceError.proto\x1a\x15scalapb/scalapb.proto\" \n\x0cServiceError\x12\x10\n\x08messages\x18\x01 \x03(\tB\"\xe2?\x1f\n\x1b\x63oop.rchain.casper.protocolH\x00\x62\x06proto3')



_SERVICEERROR = DESCRIPTOR.message_types_by_name['ServiceError']
ServiceError = _reflection.GeneratedProtocolMessageType('ServiceError', (_message.Message,), {
  'DESCRIPTOR' : _SERVICEERROR,
  '__module__' : 'ServiceError_pb2'
  # @@protoc_insertion_point(class_scope:ServiceError)
  })
_sym_db.RegisterMessage(ServiceError)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\342?\037\n\033coop.rchain.casper.protocolH\000'
  _SERVICEERROR._serialized_start=45
  _SERVICEERROR._serialized_end=77
# @@protoc_insertion_point(module_scope)
