#!/bin/sh
set -e

src_dir=protobuf
out_dir=rchain/pb
stub_dir=rchain/pb

mkdir -p $out_dir
python -m grpc_tools.protoc \
	-I $src_dir \
	--python_out=$out_dir \
	--grpc_python_out=$out_dir \
	--mypy_out=$stub_dir \
	$(find $src_dir -name '*.proto')

# https://github.com/protocolbuffers/protobuf/issues/1491#issuecomment-438138293
sed -i -E \
	-e 's/^import.*_pb2/from . \0/' \
	-e 's/^from scalapb/from .scalapb/' \
	$(find $out_dir -name '*.py')

sed -i -E \
	-e 's/^from (.*_pb2)/from .\1/' \
	$(find $out_dir -name '*.pyi')
