# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
    FieldDescriptor as google___protobuf___descriptor___FieldDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    List as typing___List,
    Optional as typing___Optional,
    Text as typing___Text,
    Tuple as typing___Tuple,
    cast as typing___cast,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


class ScalaPbOptions(google___protobuf___message___Message):
    class OptionsScope(int):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        @classmethod
        def Name(cls, number: int) -> str: ...
        @classmethod
        def Value(cls, name: str) -> ScalaPbOptions.OptionsScope: ...
        @classmethod
        def keys(cls) -> typing___List[str]: ...
        @classmethod
        def values(cls) -> typing___List[ScalaPbOptions.OptionsScope]: ...
        @classmethod
        def items(cls) -> typing___List[typing___Tuple[str, ScalaPbOptions.OptionsScope]]: ...
        FILE = typing___cast(ScalaPbOptions.OptionsScope, 0)
        PACKAGE = typing___cast(ScalaPbOptions.OptionsScope, 1)
    FILE = typing___cast(ScalaPbOptions.OptionsScope, 0)
    PACKAGE = typing___cast(ScalaPbOptions.OptionsScope, 1)

    package_name = ... # type: typing___Text
    flat_package = ... # type: bool
    preamble = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text]
    single_file = ... # type: bool
    no_primitive_wrappers = ... # type: bool
    primitive_wrappers = ... # type: bool
    collection_type = ... # type: typing___Text
    preserve_unknown_fields = ... # type: bool
    object_name = ... # type: typing___Text
    scope = ... # type: ScalaPbOptions.OptionsScope
    lenses = ... # type: bool
    retain_source_code_info = ... # type: bool
    map_type = ... # type: typing___Text
    test_only_no_java_conversions = ... # type: bool

    def __init__(self,
        *,
        package_name : typing___Optional[typing___Text] = None,
        flat_package : typing___Optional[bool] = None,
        preamble : typing___Optional[typing___Iterable[typing___Text]] = None,
        single_file : typing___Optional[bool] = None,
        no_primitive_wrappers : typing___Optional[bool] = None,
        primitive_wrappers : typing___Optional[bool] = None,
        collection_type : typing___Optional[typing___Text] = None,
        preserve_unknown_fields : typing___Optional[bool] = None,
        object_name : typing___Optional[typing___Text] = None,
        scope : typing___Optional[ScalaPbOptions.OptionsScope] = None,
        lenses : typing___Optional[bool] = None,
        retain_source_code_info : typing___Optional[bool] = None,
        map_type : typing___Optional[typing___Text] = None,
        test_only_no_java_conversions : typing___Optional[bool] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> ScalaPbOptions: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"collection_type",u"flat_package",u"lenses",u"map_type",u"no_primitive_wrappers",u"object_name",u"package_name",u"preserve_unknown_fields",u"primitive_wrappers",u"retain_source_code_info",u"scope",u"single_file",u"test_only_no_java_conversions"]) -> bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"collection_type",u"flat_package",u"import",u"lenses",u"map_type",u"no_primitive_wrappers",u"object_name",u"package_name",u"preamble",u"preserve_unknown_fields",u"primitive_wrappers",u"retain_source_code_info",u"scope",u"single_file",u"test_only_no_java_conversions"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"collection_type",b"collection_type",u"flat_package",b"flat_package",u"lenses",b"lenses",u"map_type",b"map_type",u"no_primitive_wrappers",b"no_primitive_wrappers",u"object_name",b"object_name",u"package_name",b"package_name",u"preserve_unknown_fields",b"preserve_unknown_fields",u"primitive_wrappers",b"primitive_wrappers",u"retain_source_code_info",b"retain_source_code_info",u"scope",b"scope",u"single_file",b"single_file",u"test_only_no_java_conversions",b"test_only_no_java_conversions"]) -> bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"collection_type",b"collection_type",u"flat_package",b"flat_package",u"import",b"import",u"lenses",b"lenses",u"map_type",b"map_type",u"no_primitive_wrappers",b"no_primitive_wrappers",u"object_name",b"object_name",u"package_name",b"package_name",u"preamble",b"preamble",u"preserve_unknown_fields",b"preserve_unknown_fields",u"primitive_wrappers",b"primitive_wrappers",u"retain_source_code_info",b"retain_source_code_info",u"scope",b"scope",u"single_file",b"single_file",u"test_only_no_java_conversions",b"test_only_no_java_conversions"]) -> None: ...

class MessageOptions(google___protobuf___message___Message):
    extends = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text]
    companion_extends = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text]
    annotations = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text]
    type = ... # type: typing___Text
    companion_annotations = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text]
    sealed_oneof_extends = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text]

    def __init__(self,
        *,
        extends : typing___Optional[typing___Iterable[typing___Text]] = None,
        companion_extends : typing___Optional[typing___Iterable[typing___Text]] = None,
        annotations : typing___Optional[typing___Iterable[typing___Text]] = None,
        type : typing___Optional[typing___Text] = None,
        companion_annotations : typing___Optional[typing___Iterable[typing___Text]] = None,
        sealed_oneof_extends : typing___Optional[typing___Iterable[typing___Text]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> MessageOptions: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"type"]) -> bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"annotations",u"companion_annotations",u"companion_extends",u"extends",u"sealed_oneof_extends",u"type"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"type",b"type"]) -> bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"annotations",b"annotations",u"companion_annotations",b"companion_annotations",u"companion_extends",b"companion_extends",u"extends",b"extends",u"sealed_oneof_extends",b"sealed_oneof_extends",u"type",b"type"]) -> None: ...

class FieldOptions(google___protobuf___message___Message):
    type = ... # type: typing___Text
    scala_name = ... # type: typing___Text
    collection_type = ... # type: typing___Text
    key_type = ... # type: typing___Text
    value_type = ... # type: typing___Text
    annotations = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text]
    map_type = ... # type: typing___Text
    no_box = ... # type: bool

    def __init__(self,
        *,
        type : typing___Optional[typing___Text] = None,
        scala_name : typing___Optional[typing___Text] = None,
        collection_type : typing___Optional[typing___Text] = None,
        key_type : typing___Optional[typing___Text] = None,
        value_type : typing___Optional[typing___Text] = None,
        annotations : typing___Optional[typing___Iterable[typing___Text]] = None,
        map_type : typing___Optional[typing___Text] = None,
        no_box : typing___Optional[bool] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> FieldOptions: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"collection_type",u"key_type",u"map_type",u"no_box",u"scala_name",u"type",u"value_type"]) -> bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"annotations",u"collection_type",u"key_type",u"map_type",u"no_box",u"scala_name",u"type",u"value_type"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"collection_type",b"collection_type",u"key_type",b"key_type",u"map_type",b"map_type",u"no_box",b"no_box",u"scala_name",b"scala_name",u"type",b"type",u"value_type",b"value_type"]) -> bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"annotations",b"annotations",u"collection_type",b"collection_type",u"key_type",b"key_type",u"map_type",b"map_type",u"no_box",b"no_box",u"scala_name",b"scala_name",u"type",b"type",u"value_type",b"value_type"]) -> None: ...

class EnumOptions(google___protobuf___message___Message):
    extends = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text]
    companion_extends = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text]
    type = ... # type: typing___Text

    def __init__(self,
        *,
        extends : typing___Optional[typing___Iterable[typing___Text]] = None,
        companion_extends : typing___Optional[typing___Iterable[typing___Text]] = None,
        type : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> EnumOptions: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"type"]) -> bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"companion_extends",u"extends",u"type"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"type",b"type"]) -> bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"companion_extends",b"companion_extends",u"extends",b"extends",u"type",b"type"]) -> None: ...

class EnumValueOptions(google___protobuf___message___Message):
    extends = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text]

    def __init__(self,
        *,
        extends : typing___Optional[typing___Iterable[typing___Text]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> EnumValueOptions: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"extends"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"extends",b"extends"]) -> None: ...

class OneofOptions(google___protobuf___message___Message):
    extends = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text]

    def __init__(self,
        *,
        extends : typing___Optional[typing___Iterable[typing___Text]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> OneofOptions: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"extends"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"extends",b"extends"]) -> None: ...

options = ... # type: google___protobuf___descriptor___FieldDescriptor

message = ... # type: google___protobuf___descriptor___FieldDescriptor

field = ... # type: google___protobuf___descriptor___FieldDescriptor

enum_options = ... # type: google___protobuf___descriptor___FieldDescriptor

enum_value = ... # type: google___protobuf___descriptor___FieldDescriptor

oneof = ... # type: google___protobuf___descriptor___FieldDescriptor
